#!/usr/bin/env python3
"""visualize.py

Load the MFCC feature matrix (X.npy) and labels (y.npy) generated by
`extract_features.py` and produce a comparison plot of the average 13‑dimensional
MFCC values for the two classes:

* **evet** (label 1) – plotted in one color
* **hayir** (label 0) – plotted in a different color

The plot is saved as `mfcc_comparison.png`.
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Use a clean visual style
sns.set(style="whitegrid")

BASE_DIR = os.path.abspath(os.path.dirname(__file__))
DATASET_DIR = os.path.join(BASE_DIR, "dataset")
X_PATH = os.path.join(DATASET_DIR, "X.npy")
Y_PATH = os.path.join(DATASET_DIR, "y.npy")

def load_data():
    """Load X and y arrays from the dataset folder."""
    X = np.load(X_PATH)
    y = np.load(Y_PATH)
    return X, y

def compute_class_means(X, y):
    """Return mean MFCC vectors for the two classes.

    Returns:
        evet_mean (np.ndarray): mean of samples where label == 1
        hayir_mean (np.ndarray): mean of samples where label == 0
    """
    evet_mean = X[y == 1][:, 1:].mean(axis=0) if np.any(y == 1) else np.zeros(12)
    hayir_mean = X[y == 0][:, 1:].mean(axis=0) if np.any(y == 0) else np.zeros(12)
    return evet_mean, hayir_mean

def plot_comparison(evet_mean, hayir_mean):
    """Create a line plot comparing the two mean MFCC vectors and save it."""
    coeff_idx = np.arange(2, 14)  # MFCC indices 2-13
    plt.figure(figsize=(10, 6))
    plt.plot(coeff_idx, evet_mean, marker='o', label='evet (yes)', color='tab:blue')
    plt.plot(coeff_idx, hayir_mean, marker='s', label='hayir (no)', color='tab:orange')
    plt.title('Average MFCC Coefficients per Class')
    plt.xlabel('MFCC coefficient index')
    plt.ylabel('Mean coefficient value')
    plt.xticks(coeff_idx)
    plt.legend()
    plt.tight_layout()
    out_path = os.path.join(BASE_DIR, "mfcc_comparison.png")
    plt.savefig(out_path, dpi=300)
    plt.close()
    print(f"Plot saved to {out_path}")

def main():
    X, y = load_data()
    evet_mean, hayir_mean = compute_class_means(X, y)
    print(f"Average MFCC for evet (label 1): {evet_mean}")
    print(f"Average MFCC for hayir (label 0): {hayir_mean}")
    plot_comparison(evet_mean, hayir_mean)

if __name__ == "__main__":
    main()
